version: '3.8'

services:
# --------------------------
# Service PostgreSQL
# --------------------------
  postgres:
    image: postgres:14
    container_name: quartissimo-postgres
    restart: always
    environment:
      POSTGRES_DB: quartissimo_db
      POSTGRES_USER: quartissimo_user
      POSTGRES_PASSWORD: quartissimo_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # --------------------------
  # Service MongoDB
  # --------------------------
  mongodb:
    image: mongo:6
    container_name: quartissimo-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # ================
  #  BACKEND
  # ================
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: quartissimo-backend
    ports:
      - "3000:3000"
    # Si tu as des variables d'environnement spécifiques
    environment:
      PORT: 3000
    volumes:
      - ./backend:/app

  # ================
  #  FRONTEND
  # ================
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: quartissimo-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    # Optionnellement, si tu appelles le backend par exemple avec REACT_APP_BACKEND_URL
    environment:
      REACT_APP_BACKEND_URL: "http://localhost:3000"
    volumes:
      - ./frontend:/app

# --------------------------
# Volumes persistant
# --------------------------
volumes:
  postgres_data:
  mongo_data:
