services:
  postgres:
    image: postgres:latest
    container_name: quartissimo-postgres
    environment:
      POSTGRES_DB: quartissimo_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: V3Gry9LUU9umyy+*
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer_ui
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      ADMINER_DEFAULT_SERVER: postgres

  mongodb:
    image: mongo:latest
    container_name: quartissimo-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    container_name: quartissimo-backend
    build:
      context: ./backend
    volumes:
      - ./backend/src:/app/src
    ports:
      - "3000:3000"
    environment:
      - DB_NAME=quartissimo_db
      - DB_PASSWORD=V3Gry9LUU9umyy+*
      - DB_USER=admin
      - DB_SYNCHRONISE=true
      - DB_HOST=postgres
    depends_on:
      - postgres

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: quartissimo-frontend
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - backend
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true  # Pour la détection des changements
  #     - WDS_SOCKET_PORT=0   
  #     - REACT_APP_BACKEND_URL=http://localhost:3000
  #   volumes:
  #     - ./frontend:/app    # Ce volume est crucial pour le hot-reload
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: quartissimo-frontend
    ports:
      - "80:3000"
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true  # Pour la détection des changements
      - WDS_SOCKET_PORT=0   
      - REACT_APP_BACKEND_URL=http://localhost:3000
    volumes:
      - ./frontend:/app    # Ce volume est crucial pour le hot-reload
      - /app/node_modules

volumes:
  postgres_data:
  mongo_data:
