FROM node:16-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Build the app for production
RUN npm run build

# Install serve to run the production build
RUN npm install -g serve

# Exposer le port pour le développement
EXPOSE 3000

ENV CHOKIDAR_USEPOLLING=true
ENV WATCHPACK_POLLING=true

# Run the production build with serve
CMD ["serve", "-s", "build", "-l", "3000"]